fix: changeset typo
When an unknown package is referenced in a changeset file, this error
shows up in the pipeline logs

> TypeError: Cannot destructure property 'packageJson' of 'undefined' as
it is undefined.

In this instance there was a typo `components` instead of `component`
which is a good indication that using

```shell
pnpm changeset
```

is probable the best way to generate these files